spring:
  # Configuration pour environnement de développement avec PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/newsplatform_dev
    username: newsuser
    password: G7!pR2@vLq8z
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
      connection-timeout: 3000
      maximum-pool-size: 10

  jpa:
    hibernate:
      ddl-auto: validate  # Utiliser Flyway, pas create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Suppression du dialect explicite pour éviter le warning

  # Activer Flyway pour PostgreSQL (remplace les données H2)
  flyway:
    enabled: true
    locations: classpath:db/migration

# Logs détaillés pour dev
logging:
  level:
    com.newsplatform: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    root: INFO

# JWT pour dev (clé sécurisée pour HS512)
jwt:
  secret: dev-secret-key-for-testing-only-not-for-production-must-be-at-least-64-bytes-long-for-hs512-algorithm
  expiration: 86400000 # 24 hours
  refresh-expiration: 604800000 # 7 days

# Désactiver complètement le nettoyage des logs en dev pour éviter les problèmes de démarrage
app:
  logs:
    cleanup:
      enabled: false
